[package]
name = "sbs5k_engine"
version = "0.1.0"
edition = "2021"

[dependencies]
gl = "^0.14.0"
glfw = "^0.51.0"
glm = "^0.2.3"
image = "^0.24.5"
nalgebra = { version = "^0.32.2", features = ["serde-serialize"] }

[dev-dependencies]
rstest = "^0.16.0"
